'use client';
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "../components/navbar";
import { BasketProvider } from "../contexts/BasketContext";
import { AdminAuthProvider } from "../contexts/AdminAuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BasketProvider>
          <AdminAuthProvider>
            <NavBar />
            <main className="pt-20">{/* Padding top to offset fixed navbar */}
            {children}
            </main>
          </AdminAuthProvider>
        </BasketProvider>
      </body>
    </html>
  );
}
